# Worker App Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: worker-app
  namespace: ns-worker-app
  labels:
    app: worker-app
  annotations:
    iam.gke.io/gcp-service-account: worker-app-sa-prd@burner-arnsengu.iam.gserviceaccount.com