# Vote App Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: voting-app
  namespace: ns-vote-app
  labels:
    app: vote-app
  annotations:
    iam.gke.io/gcp-service-account: voting-app-sa-prd@burner-arnsengu.iam.gserviceaccount.com