# Namespaces for the voting app
---
apiVersion: v1
kind: Namespace
metadata:
  name: voting-app
  labels:
    name: voting-app
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    name: observability
